# Select a networking backend. Can be 'flannel', 'gobgp', 'bird', 'none'
networking: bird

# Select an ipam plugin. Can be `calico-ipam` or `host-local`
ipam: calico-ipam

datastore:
  # Can be selfHostedEtcd, byoEtcd, or kubernetes
  type: selfHostedEtcd
  location: http://10.96.232.136:6666

# Kubernetes Major.Minor version. No revision!
# kubernetesVersion: v1.7

kubeadmRbac: true